server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 1234

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: alex.yb.dev@gmail.com
    password: wtyo evjm qcix gudq
    default-encoding: utf-8
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    com.finance.stockhub : debug
    org.hibernate.type : trace
